exclude: "(^migrations/+.|^tests/+.|^venv/+.|^.venv/+.|^env/+.|^.tox/+.|^build/+.|docs)"
repos:
  {{'''- repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff''' if cookiecutter.ruff else ''}}
  {{'''- repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
  ''' if cookiecutter.autoflake else ''}}
  {{'''- repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: check-toml''' if cookiecutter.pre_commit_hooks else ''}}
  {{'''- repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint''' if cookiecutter.darglint else ''}}
  {{'''- repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports''' if cookiecutter.reorder_python_imports else ''}}
  {{'''- repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln''' if cookiecutter.pycln else ''}}
  {{'''- repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade''' if cookiecutter.pyupgrade else ''}}
  {{'''- repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=79]''' if cookiecutter.black else ''}}
  {{'''- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]''' if cookiecutter.mypy else ''}}
  {{'''- repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint''' if cookiecutter.pylint else ''}}
  {{'''- repo: local
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-bandit
          - flake8-annotations
          - flake8-docstrings
        name: flake8
        description: Python style guide enforcement
        entry: flake8p
        language: python
        types: [python]''' if cookiecutter.flake else ''}}
